### ISSUE TITLE
ERROR:Error occurred when estimating parameters for /bimeng.fa; it's skipped

### ISSUE THREAD

**Issue by Liuxuanzeng** [shahab-sarmashghi/RESPECT#20]
Dear Professor,
I encountered an error when running respect. Here is the command I ran. Thanks for your help.
There is also a small question. The -I parameter provides a histogram. Does not using this parameter affect the results?

(py38) liuxuanzeng@try-MZ72-HB0-00:~/software/RESPECT/RESPECT$ respect -i ../../../singele_copyGS/genomedata/bimeng.fa -d /home/liuxuanzeng/software/RESPECT/RESPECT/bimengout/ -N 10 --debug
2024-11-14 20:14:39,733 INFO:Processing bimeng.fa...
2024-11-14 20:24:29,237 INFO:compute_kmer_histogram finished in 323.02898812294006 seconds
2024-11-14 20:24:29,486 INFO:estimate_genome_skim_parameters finished in 0.21205830574035645 seconds
2024-11-14 20:24:29,487 ERROR:Error occurred when estimating parameters for /home/liuxuanzeng/singele_copyGS/genomedata/bimeng.fa; it's skipped
Traceback (most recent call last):
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/paramter_estimator.py", line 344, in __call__
    return self.estimate_genomic_parameters(*args, **kwargs)
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/paramter_estimator.py", line 326, in estimate_genomic_parameters
    self.estimate_genome_skim_parameters(spectra_number, error_norm, iterations_number, min_r1l, temperature)
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/timer.py", line 68, in wrapper_timer
    return func(*args, **kwargs)
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/paramter_estimator.py", line 281, in estimate_genome_skim_parameters
    optimizer.run_simulated_annealing(iterations_number, min_r1l, temperature)
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/optimizer.py", line 378, in run_simulated_annealing
    self.save_iteration_results(0)
  File "/home/liuxuanzeng/miniconda3/envs/py38/lib/python3.8/site-packages/respect-1.3.0-py3.8.egg/respect/optimizer.py", line 234, in save_iteration_results
    self._parameters_dataframe = self._parameters_dataframe.append(
  File "/home/liuxuanzeng/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
2024-11-14 20:24:29,490 ERROR:Error occurred while trying to get estimated parameters for a sample
2024-11-14 20:24:29,498 INFO:Writing the results to the output files...

**Comment by shahab-sarmashghi** [comment]
Hi,

Thank you for reaching out. It seems the error is that the newer versions of pandas have removed `append()` method. I will update the code and make a release to address this but in the meantime you can downgrade your pandas version to `1.x` and trying again.

**Comment by Liuxuanzeng** [comment]
Dear Professor,
Thanks for your help, looking forward to the new version.
There seems to be a new problem, which is whether it is a license issue.

(py37_RESPECT) liuxuanzeng@try-MZ72-HB0-00:~/software/RESPECT/RESPECT/Eocu$ respect -i Eocu_2G.fa -o /home/liuxuanzeng/software/RESPECT/RESPECT/Eocu/Eocu_out/  -N 10 --debug
2024-11-15 22:08:01,368 INFO:Processing Eocu_2G.fa...
2024-11-15 22:09:54,200 INFO:compute_kmer_histogram finished in 54.27926301956177 seconds
2024-11-15 22:09:54,415 INFO:Starting iterations to estimate parameters of Eocu_2G.fa
License expired 2024-10-28
2024-11-15 22:09:54,690 INFO:estimate_genome_skim_parameters finished in 0.4587686061859131 seconds
2024-11-15 22:09:54,690 ERROR:Error occurred when estimating parameters for /home/liuxuanzeng/software/RESPECT/RESPECT/Eocu/Eocu_2G.fa; it's skipped
Traceback (most recent call last):
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/paramter_estimator.py", line 344, in __call__
    return self.estimate_genomic_parameters(*args, **kwargs)
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/paramter_estimator.py", line 326, in estimate_genomic_parameters
    self.estimate_genome_skim_parameters(spectra_number, error_norm, iterations_number, min_r1l, temperature)
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/timer.py", line 68, in wrapper_timer
    return func(*args, **kwargs)
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/paramter_estimator.py", line 281, in estimate_genome_skim_parameters
    optimizer.run_simulated_annealing(iterations_number, min_r1l, temperature)
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/optimizer.py", line 395, in run_simulated_annealing
    repeat_spectra_next = self.estimate_repeat_spectra(o[1:], poisson_matrix_next[1:, :])
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/optimizer.py", line 336, in estimate_repeat_spectra
    n_splines)]
  File "/home/liuxuanzeng/miniconda3/envs/py37_RESPECT/lib/python3.7/site-packages/respect-1.3.0-py3.7.egg/respect/optimizer.py", line 335, in <listcomp>
    spectral_residuals = [1.0 * constrained_spectra[i] / norm(constrained_spectra[i:], ord=1) for i in range(
TypeError: 'NoneType' object is not subscriptable
2024-11-15 22:09:54,692 ERROR:Error occurred while trying to get estimated parameters for a sample
2024-11-15 22:09:54,742 INFO:Writing the results to the output files...

**Comment by shahab-sarmashghi** [comment]
Hi,

Yes, it seems your Gurobi license has expired and needs to be renewed.
